language: ruby

# Travis does not build the gh-pages branch by default, so we add it to the safelist
# https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
branches:
  only:
    gh-pages

install:
  - gem install awesome_bot

script:
  - awesome_bot README.md

notifications:
  email:
    on_success: never
